name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dev
  path_provider: ^1.6.27  # conventional pths such as temp
  get_it: ^5.0.6  # constructor set
  injectable: ^1.0.7  # with get_it
  path: ^1.7.0  # path util
  uuid: ^2.2.2
  equatable: ^1.2.6  # equality
  intl: ^0.16.1
  logger: ^0.9.4
  json_serializable: ^3.5.1
  image_picker: ^0.6.7+22
  multi_image_picker: ^4.7.15
  photo_view: ^0.10.3
  # State management
  provider: ^4.3.3
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  # Functionalities
  share: ^0.6.5+4
  flutter_local_notifications: ^4.0.1+1
  android_alarm_manager: ^0.4.5+20
  flutter_secure_storage: ^3.3.5  # keychain
  url_launcher: ^5.7.10
  file_picker: ^2.1.6  # use the native file explorer to pick single or multiple files, with extensions filtering support.
  # Persistence
  shared_preferences: ^0.5.12+4  # app local storage
  sqflite: ^1.3.2+3  # sqllite
  # UI
  # Icons/Font
  cupertino_icons: ^1.0.0  # use with the CupertinoIcons class for iOS style icons.
  google_fonts: ^1.1.2
  # Effects
  auto_size_text: ^2.1.0  # automatically resizes text to fit perfectly within its bounds.
  octo_image: ^0.3.0  # placeholders, error widgets and transform your image.
  pull_to_refresh: ^1.6.4  # scroll component drop-down refresh and pull up load
  responsive_builder: ^0.3.0
  # Components
  flutter_datetime_picker: ^1.5.0
  flutter_picker: ^1.1.5
  convex_bottom_bar: ^2.6.0  # bottom tab with  n animation
  curved_navigation_bar: ^0.3.7  # curved navigation bar.
  flutter_slidable: ^0.5.7  # slidable card widget like an email app
  carousel_slider: ^3.0.0  # card carousel
  flutter_swiper: ^1.1.6
  table_calendar: ^2.3.3
  modal_bottom_sheet: ^1.0.0+1
  # Animations
  shimmer: ^1.1.2  # shimmer effect
  animations: ^1.1.2  # pre-canned animations for commonly-desired effects
  animated_text_kit: ^3.1.0
  page_transition: ^1.1.7+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  injectable_generator: ^1.0.7
  mobx_codegen: ^1.1.2
  json_annotation: ^3.1.1
  pedantic: ^1.9.2  # lint and etc

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
